//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing
    {
        public int id { get; set; }
        public string identifier { get; set; }
        public string sender { get; set; }
        public string target_type { get; set; }
        public string target { get; set; }
        public string label { get; set; }
        public int amount { get; set; }
    }
}
