//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class black_shipments
    {
        public int b_id { get; set; }
        public Nullable<int> id { get; set; }
        public string identifier { get; set; }
        public string label { get; set; }
        public string item { get; set; }
        public string price { get; set; }
        public string count { get; set; }
        public Nullable<int> time { get; set; }
    }
}
