//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class disc_inventory_itemdata
    {
        public decimal id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int weight { get; set; }
        public bool closeonuse { get; set; }
        public int max { get; set; }
    }
}
