//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dpkeybinds
    {
        public int d_id { get; set; }
        public string id { get; set; }
        public string keybind1 { get; set; }
        public string emote1 { get; set; }
        public string keybind2 { get; set; }
        public string emote2 { get; set; }
        public string keybind3 { get; set; }
        public string emote3 { get; set; }
        public string keybind4 { get; set; }
        public string emote4 { get; set; }
        public string keybind5 { get; set; }
        public string emote5 { get; set; }
        public string keybind6 { get; set; }
        public string emote6 { get; set; }
    }
}
