//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class hastane
    {
        public int id { get; set; }
        public string Sender { get; set; }
        public string Type { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Reciever { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
