//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        public string name { get; set; }
        public string label { get; set; }
        public double weight { get; set; }
        public bool rare { get; set; }
        public bool can_remove { get; set; }
        public int price { get; set; }
    }
}
