//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_grades
    {
        public int id { get; set; }
        public string job_name { get; set; }
        public int grade { get; set; }
        public string name { get; set; }
        public string label { get; set; }
        public int salary { get; set; }
        public string skin_male { get; set; }
        public string skin_female { get; set; }
    }
}
