//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kaiser_ciuchy
    {
        public int id { get; set; }
        public string identifier { get; set; }
        public int bag { get; set; }
        public int bag2 { get; set; }
        public int tshirt { get; set; }
        public int tshirt2 { get; set; }
        public int torso { get; set; }
        public int torso2 { get; set; }
        public int legs { get; set; }
        public int legs2 { get; set; }
        public int shoes { get; set; }
        public int shoes2 { get; set; }
        public int arms { get; set; }
        public int chain { get; set; }
        public int chain2 { get; set; }
        public int mask { get; set; }
        public int mask2 { get; set; }
        public int decals { get; set; }
        public int decals2 { get; set; }
        public int hat { get; set; }
        public int hat2 { get; set; }
        public int glasses { get; set; }
        public int glasses2 { get; set; }
    }
}
