//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class launcher_ayarlar
    {
        public int ayarlar_id { get; set; }
        public string arkaplan_resmi { get; set; }
        public string sol_logo { get; set; }
        public string team_ip { get; set; }
        public string discord_adres { get; set; }
        public string sunucu_port { get; set; }
        public string sunucu_ip { get; set; }
        public string team_port { get; set; }
        public string forum_adres { get; set; }
        public int sol_renk { get; set; }
        public int main_renk { get; set; }
        public int sag_renk { get; set; }
    
        public virtual launcher_renk launcher_renk { get; set; }
        public virtual launcher_renk launcher_renk1 { get; set; }
        public virtual launcher_renk launcher_renk2 { get; set; }
    }
}
