//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class launcher_duyurular
    {
        public int duyuru_id { get; set; }
        public string duyuru_baslik { get; set; }
        public string duyuru_metin { get; set; }
        public System.DateTime duyuru_tarih { get; set; }
    }
}
