//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class launcher_renk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public launcher_renk()
        {
            this.launcher_ayarlar = new HashSet<launcher_ayarlar>();
            this.launcher_ayarlar1 = new HashSet<launcher_ayarlar>();
            this.launcher_ayarlar2 = new HashSet<launcher_ayarlar>();
        }
    
        public int renk_id { get; set; }
        public Nullable<int> red { get; set; }
        public Nullable<int> green { get; set; }
        public Nullable<int> blue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<launcher_ayarlar> launcher_ayarlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<launcher_ayarlar> launcher_ayarlar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<launcher_ayarlar> launcher_ayarlar2 { get; set; }
    }
}
