//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdt_warrants
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> char_id { get; set; }
        public Nullable<int> report_id { get; set; }
        public string report_title { get; set; }
        public string charges { get; set; }
        public string date { get; set; }
        public string expire { get; set; }
        public string notes { get; set; }
        public string author { get; set; }
    }
}
