//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class outfits
    {
        public int id { get; set; }
        public string idSteam { get; set; }
        public int dad { get; set; }
        public int mum { get; set; }
        public int dadmumpercent { get; set; }
        public int skinton { get; set; }
        public int eyecolor { get; set; }
        public int acne { get; set; }
        public int skinproblem { get; set; }
        public int freckle { get; set; }
        public int wrinkle { get; set; }
        public int wrinkleopacity { get; set; }
        public int eyebrow { get; set; }
        public int eyebrowopacity { get; set; }
        public int beard { get; set; }
        public int beardopacity { get; set; }
        public int beardcolor { get; set; }
        public int hair { get; set; }
        public int hairtext { get; set; }
        public int torso { get; set; }
        public int torsotext { get; set; }
        public int leg { get; set; }
        public int legtext { get; set; }
        public int shoes { get; set; }
        public int shoestext { get; set; }
        public int accessory { get; set; }
        public int accessorytext { get; set; }
        public int undershirt { get; set; }
        public int undershirttext { get; set; }
        public int torso2 { get; set; }
        public int torso2text { get; set; }
        public int prop_hat { get; set; }
        public int prop_hat_text { get; set; }
        public int prop_glasses { get; set; }
        public int prop_glasses_text { get; set; }
        public int prop_earrings { get; set; }
        public int prop_earrings_text { get; set; }
        public int prop_watches { get; set; }
        public int prop_watches_text { get; set; }
    }
}
