//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class owned_vehicles
    {
        public int id { get; set; }
        public string owner { get; set; }
        public string plate { get; set; }
        public string vehicle { get; set; }
        public string type { get; set; }
        public string job { get; set; }
        public bool stored { get; set; }
        public bool state { get; set; }
        public int jamstate { get; set; }
        public Nullable<int> lasthouse { get; set; }
    }
}
