//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class owned_properties
    {
        public int id { get; set; }
        public string name { get; set; }
        public double price { get; set; }
        public int rented { get; set; }
        public string owner { get; set; }
    }
}
