//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone_calls
    {
        public int id { get; set; }
        public string owner { get; set; }
        public string num { get; set; }
        public int incoming { get; set; }
        public System.DateTime time { get; set; }
        public int accepts { get; set; }
    }
}
