//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rented_vehicles
    {
        public int id { get; set; }
        public string vehicle { get; set; }
        public string plate { get; set; }
        public string player_name { get; set; }
        public int base_price { get; set; }
        public int rent_price { get; set; }
        public string owner { get; set; }
    }
}
