//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string identifier { get; set; }
        public string license { get; set; }
        public Nullable<int> money { get; set; }
        public string name { get; set; }
        public string skin { get; set; }
        public string job { get; set; }
        public Nullable<int> job_grade { get; set; }
        public string loadout { get; set; }
        public string position { get; set; }
        public Nullable<int> bank { get; set; }
        public Nullable<int> permission_level { get; set; }
        public string group { get; set; }
        public string status { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string dateofbirth { get; set; }
        public string sex { get; set; }
        public string height { get; set; }
        public string lastpos { get; set; }
        public string DmvTest { get; set; }
        public string vote { get; set; }
        public string lastdigits { get; set; }
        public int jail { get; set; }
        public Nullable<bool> is_dead { get; set; }
        public Nullable<int> isFirstConnection { get; set; }
        public string tattoos { get; set; }
        public string phone_number { get; set; }
        public string last_property { get; set; }
        public string accounts { get; set; }
        public string inventory { get; set; }
        public string last_name { get; set; }
        public string dob { get; set; }
        public Nullable<int> is_male { get; set; }
        public string accessories { get; set; }
        public string first_name { get; set; }
    }
}
