//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicles
    {
        public int id { get; set; }
        public string name { get; set; }
        public string model { get; set; }
        public int price { get; set; }
        public string category { get; set; }
        public int inshop { get; set; }
        public string imglink { get; set; }
    }
}
